---
name: Run all code checkers (style, static analysis, api versions etc.)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: run code checkers
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          make install-notests

  reproducible-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: run first build
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          make install-notests

      - name: compare builds
        env:
          MAVEN_ARGS: "-B -ff -Dbasepom.test.skip=true"
        run: |
          make compare-reproducible
