---
name: Run all tests, including slow tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  slow-tests:
    name: Run slow tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build code
        id: install_fast
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          ./mvnw --version
          make install-fast

      - id: run_slow_tests
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          ./mvnw --version
          make run-slow-tests

  slow-tests-locale:
    name: Run slow tests with different timezone and locale
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - uses: actions/setup-java@v4
        name: setup build jdk
        id: build_jdk
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: build code
        id: install_fast
        env:
          MAVEN_ARGS: "-B -ff"
        run: |
          ./mvnw --version
          make install-fast

      - id: run_slow_tests
        env:
          MAVEN_ARGS: "-B -ff -Djdbi.test.timezone=Asia/Colombo -Djdbi.test.language=tr -Djdbi.test.region=TR"
        run: |
          ./mvnw --version
          make run-slow-tests
