---
name: Test Guava versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  guava:
    name: Test Guava versions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-version: [ 33.3.1-jre, 33.2.1-jre ]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build
        env:
          MAVEN_ARGS: "-B -fae"
        run: |
          make install-fast

      - name: Test
        env:
          MAVEN_ARGS: "-B -fae -Ddep.guava.version=${{ matrix.test-version }}"
        run: |
          make run-tests
